### ISSUE TITLE
GetProgramAccounts(Async) disabled on MainNet

### ISSUE THREAD

**Issue by tratteo** [bmresearch/Solnet#310] opened 2022-01-30 10:50 UTC
I am unable to use the endpoint GetProgramAccounts using the Cluster.MainNet.
Error 401 the RPC has been disabled. 

Tried using the RPC: https://solana-api.projectserum.com, but not getting any result either.
Errors:
- Error[0]: Unable to parse json.
- Error[-32000]: Gateway timeout

**Comment by murlokito** [comment] 2022-01-30 12:15
Which program are you trying to use to fetch the program accounts? Last time I checked this wasn't disabled using `Cluster.MainNet` except for Serum and Token Program.

**Comment by tratteo** [comment] 2022-01-30 12:26
I am calling it on token metadata program: `metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s`

**Comment by tratteo** [comment] 2022-01-31 23:25
> Which program are you trying to use to fetch the program accounts? Last time I checked this wasn't disabled using `Cluster.MainNet` except for Serum and Token Program.

Any updates?

**Comment by murlokito** [comment] 2022-01-31 23:28
> > Which program are you trying to use to fetch the program accounts? Last time I checked this wasn't disabled using `Cluster.MainNet` except for Serum and Token Program.
> 
> Any updates?

I have used GetProgramAccounts today on several different RPCs without any issue, seems like those RPCs have disabled GetProgramAccounts for the token metadata program (similar to how the default public solana RPCs have disabled it for the Serum program), you should try to use the GenesysGo public RPCs.

**Comment by murlokito** [comment] 2022-02-07 14:51
It seems that currently only the GenesysGo public RPCs allow performing `GetProgramAccounts` for `metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s`. Closing this issue as it is not a bug related to the SDK.

**Closed by murlokito** 2022-02-07 14:51 UTC
