### ISSUE TITLE
[Bug] GetProgramAccountsAsync: The RPC call or parameters have been disabled.

### ISSUE THREAD

**Issue by khoangt** [bmresearch/Solnet#282] opened 2021-12-29 10:38 UTC
**Describe the bug**
_serumClient.RpcClient.GetProgramAccountsAsync( 

accounts.RawRpcRequest: {"method":"getProgramAccounts","params":["9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin",{"encoding":"base64","filters":[{"dataSize":3228},{"memcmp":{"offset":13,"bytes":"77quYg4MGneUdjgXCunt9GgM1usmrxKY31twEy3WHwcS"}},{"memcmp":{"offset":45,"bytes":"myaccccccc"}}]}],"jsonrpc":"2.0","id":21}
accounts.RawRpcResponse: {"jsonrpc":"2.0","error":{"code": 410,"message":"The RPC call or parameters have been disabled."}, "id": 21 } 

*

**Comment by tiago18c** [comment] 2021-12-29 11:41
Not a bug. Some RPC providers (in this case I'm assuming api.mainnet-beta.solana.com) disable certain RPC calls due to performance.

**Comment by khoangt** [comment] 2021-12-29 14:47
> Not a bug. Some RPC providers (in this case I'm assuming api.mainnet-beta.solana.com) disable certain RPC calls due to performance.

How to change RpcMainNet url?

**Comment by murlokito** [comment] 2021-12-29 15:01
> > Not a bug. Some RPC providers (in this case I'm assuming api.mainnet-beta.solana.com) disable certain RPC calls due to performance.
> 
> How to change RpcMainNet url?

Just pass the RPC URL to the client factory method like

`ClientFactory.GetClient("rpc-url")`

**Comment by murlokito** [comment] 2022-01-12 13:56
@khoangt Considering this isn't a bug but more about the RPC providers, can we close this?

**Closed** 2022-01-12 14:10 UTC
Labels: bug
